import type { Theme } from './types';

export const lightTheme: Theme = {
  name: 'light',
  colors: {
    background: '#ffffff',
    foreground: '#0a0a0a',
    card: '#ffffff',
    cardForeground: '#0a0a0a',
    popover: '#ffffff',
    popoverForeground: '#0a0a0a',
    primary: '#2563eb',
    primaryForeground: '#ffffff',
    secondary: '#f1f5f9',
    secondaryForeground: '#0f172a',
    muted: '#f3f4f6',
    mutedForeground: '#6b7280',
    accent: '#10b981',
    accentForeground: '#ffffff',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    border: '#e5e7eb',
    input: '#ffffff',
    ring: '#2563eb',
    selection: '#dbeafe',
  },
};

export const darkTheme: Theme = {
  name: 'dark',
  colors: {
    background: '#0a0a0a',
    foreground: '#fafafa',
    card: '#141414',
    cardForeground: '#fafafa',
    popover: '#141414',
    popoverForeground: '#fafafa',
    primary: '#3b82f6',
    primaryForeground: '#ffffff',
    secondary: '#1e293b',
    secondaryForeground: '#e2e8f0',
    muted: '#374151',
    mutedForeground: '#e5e7eb',
    accent: '#10b981',
    accentForeground: '#ffffff',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    border: '#374151',
    input: '#171717',
    ring: '#3b82f6',
    selection: '#1e3a8a',
  },
};

export const sepiaTheme: Theme = {
  name: 'sepia',
  colors: {
    background: '#faf6f0',
    foreground: '#3e2723',
    card: '#f5ede1',
    cardForeground: '#3e2723',
    popover: '#f5ede1',
    popoverForeground: '#3e2723',
    primary: '#8b6914',
    primaryForeground: '#ffffff',
    secondary: '#ede4d3',
    secondaryForeground: '#3e2723',
    muted: '#e8dcc6',
    mutedForeground: '#6d4c41',
    accent: '#6b8e23',
    accentForeground: '#ffffff',
    destructive: '#b71c1c',
    destructiveForeground: '#ffffff',
    border: '#d7ccc8',
    input: '#faf6f0',
    ring: '#8b6914',
    selection: '#ffe0b2',
  },
};

export const pinkTheme: Theme = {
  name: 'pink',
  colors: {
    background: '#fef5f9',
    foreground: '#4a1d34',
    card: '#fde8f3',
    cardForeground: '#4a1d34',
    popover: '#fde8f3',
    popoverForeground: '#4a1d34',
    primary: '#ec4899',
    primaryForeground: '#ffffff',
    secondary: '#fce7f3',
    secondaryForeground: '#500724',
    muted: '#fbcfe8',
    mutedForeground: '#be185d',
    accent: '#a855f7',
    accentForeground: '#ffffff',
    destructive: '#e11d48',
    destructiveForeground: '#ffffff',
    border: '#f9a8d4',
    input: '#fef5f9',
    ring: '#ec4899',
    selection: '#fce7f3',
  },
};

export const blueTheme: Theme = {
  name: 'blue',
  colors: {
    background: '#f0f7ff',
    foreground: '#0c2340',
    card: '#e6f2ff',
    cardForeground: '#0c2340',
    popover: '#e6f2ff',
    popoverForeground: '#0c2340',
    primary: '#2563eb',
    primaryForeground: '#ffffff',
    secondary: '#dbeafe',
    secondaryForeground: '#0c2340',
    muted: '#bfdbfe',
    mutedForeground: '#1e40af',
    accent: '#0891b2',
    accentForeground: '#ffffff',
    destructive: '#dc2626',
    destructiveForeground: '#ffffff',
    border: '#93c5fd',
    input: '#f0f7ff',
    ring: '#2563eb',
    selection: '#dbeafe',
  },
};

export const themes: Record<string, Theme> = {
  light: lightTheme,
  dark: darkTheme,
  sepia: sepiaTheme,
  pink: pinkTheme,
  blue: blueTheme,
};

export const defaultTheme = 'light';
